build:
  cuda_version: "12.1.1"
  python_packages:
    - accelerate
    - sentence-transformers
    - inferless==0.2.13
    - pydantic==2.10.2
  run:
    - "pip install torch==2.6.0 --index-url https://download.pytorch.org/whl/cu126"
